### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by iamazy** [iamazy/kafkas#1]
- [ ] 异步发送达到原生 Kafka 客户端 200w tps 的吞吐量（目前一半)
- [ ] 优雅关闭
- [ ] 事务支持
- [ ] 消费者
- [ ] API 的易用性
- [ ] 优化 [kafka-protocol](https://github.com/tychedelia/kafka-protocol-rs) 的序列化性能
- [ ] 支持 `zstd` 压缩
- [ ] 支持 `io-uring`

注意项：
1. 对性能要求比较高的的地方不能使用`tracing_subscriber`，会对吞吐量有较大影响
2. 尽量避免 clone
3. 对频繁需要生成的小对象进行池化或提前扩容
